services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: garudaco-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - garudaco-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: garudaco-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - garudaco-network

networks:
  garudaco-network:
    driver: bridge

volumes:
  backend-data: