services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: garudaco-backend-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - /app/venv  # Exclude venv from volume mount
    command: python app.py
    restart: unless-stopped
    networks:
      - garudaco-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: garudaco-frontend-dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - garudaco-network

networks:
  garudaco-network:
    driver: bridge