# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - garudaco

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Only trigger when backend files change
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Collect files for deployment
        run: |
          mkdir -p deployment-package
          cp -r backend/* deployment-package/
          # Remove unnecessary files
          rm -rf deployment-package/venv
          rm -rf deployment-package/__pycache__
          rm -rf deployment-package/*.pyc
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      # - name: Run tests
      #   working-directory: ./backend
      #   run: |
      #     source venv/bin/activate
      #     python -m pytest

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deployment-package/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D94574409A8D40C9AD374A8C451F54D2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2739E0D73DD347A3ACAAF5719B8F3819 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B5F672B4237A4BF6AB66F22F2719C630 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'garudaco'
          slot-name: 'Production'
